version: '2'
networks:
 sotera:
services:
# Uncomment reverseproxy container for HTTPS
# Add each port(s) you are proxying to the 'ports' section and remove them from the container's 'ports' section
# Add each container you are proxying to the 'depends-on' section
# reverseproxy:
#  image: soterawireless/reverse-proxy:6.0.2
#  container_name: reverseproxy
#  restart: unless-stopped
#  volumes:
#   - /home/sotera/pds/reverseproxy/logs:/etc/nginx/logs
#  depends_on:
#   - pds
#  networks:
#   - sotera
#  ports:
#   - "49161:49161"
 indexer:
  image: soterawireless/indexer:6.0.1
  container_name: indexer
  restart: unless-stopped
  volumes:
   - /home/sotera/pds/indexer/logs:/opt/solr/server/logs
   - /home/sotera/pds/indexer/indexes:/opt/solr/server/solr/mycores
   - /home/sotera/pds/indexer/resources:/opt/solr/server/resources
  networks:
   - sotera
  ports:
   - "48983:8983"
  environment:
   - SOLR_HEAP=1g
   - TZ=America/Los_Angeles
  logging:
   driver: "json-file"
   options:
    max-size: "1m"
    max-file: "1"   
 db:
  image: postgres:10
  container_name: db
  volumes:
   - /home/sotera/pds/db/data:/var/lib/postgresql/data
  restart: unless-stopped
  networks:
   - sotera
  ports:
   - "45432:5432"
  environment: 
   - POSTGRES_HOST_AUTH_METHOD=trust
  logging:
   driver: "json-file"
   options:
    max-size: "10m"
    max-file: "3"  
 logger:
  image: soterawireless/pds-logger:6.0.2
  container_name: logger
  restart: unless-stopped
  volumes:
   - /home/sotera/pds/logger/logs:/usr/local/tomcat/logs
   - /home/sotera/pds/logger/conf:/usr/local/tomcat/sotera/conf
  networks:
   - sotera
  environment:
   - HEAP=256m
   - HEAP_START=128m
   - TZ=America/Los_Angeles
  logging:
   driver: "json-file"
   options:
    max-size: "1m"
    max-file: "1"   
 router:
  image: soterawireless/pds-router:6.0.2
  container_name: router
  restart: unless-stopped
  volumes:
   - /home/sotera/pds/router/logs:/usr/local/tomcat/logs
   - /home/sotera/pds/router/conf:/usr/local/tomcat/sotera/conf
  networks:
   - sotera
  ports:
   - "49154:49154"
   - "49156:49156"
  environment:
   - HEAP=512m
   - HEAP_START=256m
   - TZ=America/Los_Angeles
  logging:
   driver: "json-file"
   options:
    max-size: "1m"
    max-file: "1"   
 tunnel:
  image: soterawireless/pds-tunnel:6.0.2
  container_name: tunnel
  restart: unless-stopped
  volumes:
   - /home/sotera/pds/tunnel/logs:/usr/local/tomcat/logs
   - /home/sotera/pds/tunnel/conf:/usr/local/tomcat/sotera/conf
  networks:
   - sotera
  ports:
   - "49205:49205"
  environment:
   - HEAP=512m
   - HEAP_START=256m
   - TZ=America/Los_Angeles
  logging:
   driver: "json-file"
   options:
    max-size: "1m"
    max-file: "1"   
 swupdater:
  image: soterawireless/pds-swupdater:6.0.2
  container_name: swupdater
  restart: unless-stopped
  volumes:
   - /home/sotera/pds/swupdater/logs:/usr/local/tomcat/logs
   - /home/sotera/pds/swupdater/conf:/usr/local/tomcat/sotera/conf
   - /home/sotera/pds/swupdater/swu:/sotera/swu
  networks:
   - sotera
  ports:
   - "49157:49157"
  environment:
   - HEAP=256m
   - HEAP_START=128m
   - TZ=America/Los_Angeles
  logging:
   driver: "json-file"
   options:
    max-size: "1m"
    max-file: "1"   
 vsm:
  image: soterawireless/vsm:6.0.1
  container_name: vsm
  restart: unless-stopped
  depends_on:
   - db
  volumes:
   - /home/sotera/pds/vsm/logs:/sotera/vsm/logs
  networks:
   - sotera
  ports:
   - "49301:49301"
  logging:
   driver: "json-file"
   options:
    max-size: "1m"
    max-file: "1"   
 provisioner:
  image: soterawireless/pds-provisioner:6.0.2
  container_name: provisioner
  restart: unless-stopped
  depends_on:
   - db
  volumes:
   - /home/sotera/pds/provisioner/logs:/usr/local/tomcat/logs
   - /home/sotera/pds/provisioner/conf:/usr/local/tomcat/sotera/conf
  networks:
   - sotera
  ports:
   - "49153:49153"
  environment:
   - HEAP=256m
   - HEAP_START=128m
   - TZ=America/Los_Angeles
  logging:
   driver: "json-file"
   options:
    max-size: "1m"
    max-file: "1"   
 pds:
  image: soterawireless/pds-pdr:6.0.2
  container_name: pds
  restart: unless-stopped
  depends_on:
   - db
   - indexer
   - provisioner
   - router
  volumes:
   - /home/sotera/pds/pds/logs:/usr/local/tomcat/logs
   - /home/sotera/pds/pds/conf:/usr/local/tomcat/sotera/conf
  networks:
   - sotera
  ports:
   - "49161:49161"
  environment:
   - HEAP=1g
   - HEAP_START=512m
   - TZ=America/Los_Angeles
  logging:
   driver: "json-file"
   options:
    max-size: "1m"
    max-file: "1"

############################################################################
# Optional Interop components, remove the ones that will not be used.
############################################################################

######## Interface engine ##################################################
 interface-engine:
  image: soterawireless/interface-engine:6.0.1
  container_name: interface-engine
  restart: unless-stopped
  volumes:
   - /home/sotera/pds/interface-engine/logs:/opt/mirthconnect/logs
   - /home/sotera/pds/interface-engine/appdata:/opt/mirthconnect/appdata
   - /home/sotera/pds/interface-engine/conf:/opt/mirthconnect/conf
  networks:
   - sotera
  ports:
   - "8080:8080"
   - "8443:8443"
   - "51000:51000"
   - "51001:51001"
   - "51002:51002"
   - "51003:51003"
   - "51004:51004"
   - "51006:51006"
   - "51007:51007"
  environment:
   - HEAP=512m
   - TZ=America/Los_Angeles
  logging:
   driver: "json-file"
   options:
    max-size: "10m"
    max-file: "3" 
  
 ######## EMR Publisher #####################################################
 emrpublisher:
  image: soterawireless/iop-emrpublisher:6.0.1
  container_name: emrpublisher
  restart: unless-stopped
  depends_on:
   - pds
   - interface-engine
  volumes:
   - /home/sotera/pds/emrpublisher/logs:/usr/local/tomcat/logs
   - /home/sotera/pds/emrpublisher/conf:/usr/local/tomcat/sotera/conf
  networks:
   - sotera
  ports:
   - "52000:52000"
  environment:
   - HEAP=512m
   - HEAP_START=256m
   - TZ=America/Los_Angeles
  logging:
   driver: "json-file"
   options:
    max-size: "1m"
    max-file: "1"
  
######## Open API ##########################################################
 openapi:
  image: soterawireless/iop-openapi:6.0.1
  container_name: openapi
  restart: unless-stopped
  depends_on:
   - pds
  volumes:
   - /home/sotera/pds/openapi/logs:/usr/local/tomcat/logs
   - /home/sotera/pds/openapi/conf:/usr/local/tomcat/sotera/conf
  networks:
   - sotera
  ports:
   - "49159:49159"
  environment:
   - HEAP=512m
   - HEAP_START=256m
   - TZ=America/Los_Angeles
   - "CUSTOM_OPTS=-Djavax.net.ssl.trustStore=/usr/local/tomcat/home/sotera/pds/conf/serverTrust -Djavax.net.ssl.trustStorePassword=password -Djavax.net.ssl.keyStore=/usr/local/tomcat/sotera/conf/serverKeys -Djavax.net.ssl.keyStorePassword=password"
  logging:
   driver: "json-file"
   options:
    max-size: "1m"
    max-file: "1"
      
######## InSight ##########################################################
 insight:
  image: soterawireless/insight:6.0.1
  container_name: insight
  restart: unless-stopped
  depends_on:
   - db
   - vsm
   - openapi
  volumes:
   - /home/sotera/pds/insight/logs:/usr/local/tomcat/logs
   - /home/sotera/pds/config:/config
  networks:
   - sotera
  ports:
   - "49201:8080"
  logging:
   driver: "json-file"
   options:
    max-size: "1m"
    max-file: "1"   
  environment:
   - HEAP=512m
   - APNS_CERT_LOCATION=/config/insight-apns-prod.p12
   - APNS_CERT_PASSWORD=s0T3r@9444?!
   - TZ=America/Los_Angeles
# Single Sign-On parameters below; uncomment and fill if using SSO with InSight
#   - CLIENT_ID=
#   - CLIENT_SECRET=
#   - ACCESS_TOKEN_URI=
#   - USER_AUTH_URI=
#   - JKS_FILE=
#   - JKS_PASSWORD=
#   - SSO_SIGNIN_TEXT=
#  extra_hosts:
#   - 

############################################################################
# Web RVD Related Images
############################################################################
#  webrvd-server:
#   image: soterawireless/webrvd-server:0.0.1-SNAPSHOT
#   container_name: webrvd-server
#   restart: unless-stopped
#   depends_on:
#    - authentication-service
#    - openapi
#   volumes:
#    - /home/sotera/pds/webrvd-server:/sotera/webrvd/web-server/security
#   networks:
#    - sotera
#   ports:
#    - '44202:44202'
#   environment:
#    - PRIVATE_KEY_FILE_NAME=localhost.key
#    - CERTIFICATE_FILE_NAME=localhost.crt
#    - TZ=America/Los_Angeles
#   logging:
#    driver: "json-file"
#    options:
#     max-size: "10m"
#     max-file: "3"  
#  webrvd-client:
#   image: soterawireless/webrvd-client:0.0.1-SNAPSHOT
#   container_name: webrvd-client
#   restart: unless-stopped
#   volumes:
#    - /home/sotera/pds/webrvd-client:/etc/nginx/security
#   networks:
#    - sotera
#   ports:
#    - '4200:4200'
#   environment:
#    - TZ=America/Los_Angeles
#   logging:
#    driver: "json-file"
#    options:
#     max-size: "10m"
#     max-file: "3"  
#  database-service:
#   image: soterawireless/database-service:0.0.1-SNAPSHOT
#   container_name: database-service
#   depends_on:
#    - db
#   restart: unless-stopped
#   networks:
#    - sotera
#   ports:
#    - "44204:44204"
#   environment:
#    - TZ=America/Los_Angeles
#   logging:
#    driver: "json-file"
#    options:
#     max-size: "10m"
#     max-file: "3"  
#  authentication-service:
#   image: soterawireless/authentication-service:0.0.1-SNAPSHOT
#   container_name: authentication-service
#   depends_on:
#    - db
#   restart: unless-stopped
#   volumes:
#    - /home/sotera/pds/authentication-service:/sotera/authentication-service/security
#   networks:
#    - sotera
#   ports:
#    - '44203:44203'
#   environment:
#    - PRIVATE_KEY_FILE_NAME=localhost.key
#    - PUBLIC_KEY_FILE_NAME=localhost.crt
#    - TZ=America/Los_Angeles
#   logging:
#    driver: "json-file"
#    options:
#     max-size: "10m"
#     max-file: "3"